'use strict';

angular
    .module('insightApp')
    .controller('EmployeesCtrl', EmployeesCtrl);

function EmployeesCtrl($scope, Employees) {
    $scope.title = 'Employees overview';
    $scope.employees = Employees.getAll();
    //[{ "id": 0, "firstName": "Srdjan", "lastName": "Pajic", "displayName": "Srdjan Pajic", "profileImageUrl": "img2.jpg", "role": "Software Developer", "skills": [{ "id": 0, "name": "C#" }, { "id": 0, "name": "MVC" }, { "id": 0, "name": "Azure" }, { "id": 0, "name": "AngularJS" }], "Additionalroles": [], "Gender": 0 }, { "id": 0, "firstName": "Carlos", "lastName": "Pascual", "displayName": "Carlos Pascual", "profileImageUrl": "img2.jpg", "role": "Software Developer", "skills": [{ "id": 0, "name": "C#" }, { "id": 0, "name": "MVC" }, { "id": 0, "name": "Azure" }, { "id": 0, "name": "AngularJS" }], "Additionalroles": [], "Gender": 0 }, { "id": 0, "firstName": "Janko", "lastName": "Medjugorac", "displayName": "Janko Medjugorac", "profileImageUrl": "img2.jpg", "role": "Software Developer", "skills": [{ "id": 0, "name": "C#" }, { "id": 0, "name": "MVC" }, { "id": 0, "name": "Azure" }, { "id": 0, "name": "AngularJS" }], "Additionalroles": [], "Gender": 0 }, { "id": 0, "firstName": "Dmitry", "lastName": "Popov", "displayName": "Dmitry Popov", "profileImageUrl": "img2.jpg", "role": "Software Developer", "skills": [{ "id": 0, "name": "C#" }, { "id": 0, "name": "MVC" }, { "id": 0, "name": "Azure" }, { "id": 0, "name": "AngularJS" }], "Additionalroles": [], "Gender": 0 }, { "id": 0, "firstName": "Georg", "lastName": "Pfeiffer", "displayName": "Georg Pfeiffer", "profileImageUrl": "img2.jpg", "role": "Software Developer", "skills": [{ "id": 0, "name": "C#" }, { "id": 0, "name": "MVC" }, { "id": 0, "name": "Azure" }, { "id": 0, "name": "AngularJS" }], "Additionalroles": [], "Gender": 0 }, { "id": 0, "firstName": "Josef", "lastName": "Heidegger", "displayName": "Josef Heidegger", "profileImageUrl": "img2.jpg", "role": "Software Developer", "skills": [{ "id": 0, "name": "C#" }, { "id": 0, "name": "MVC" }, { "id": 0, "name": "Azure" }, { "id": 0, "name": "AngularJS" }], "Additionalroles": [], "Gender": 0 }, { "id": 0, "firstName": "Erika", "lastName": "Kuskova", "displayName": "Erika Kuskova", "profileImageUrl": "img3.jpg", "role": "Software Developer", "skills": [{ "id": 0, "name": "C#" }, { "id": 0, "name": "MVC" }, { "id": 0, "name": "Azure" }, { "id": 0, "name": "AngularJS" }], "Additionalroles": [], "Gender": 0 }, { "id": 0, "firstName": "Jelena", "lastName": "Stankov", "displayName": "Jelena Stankov", "profileImageUrl": "img1.jpg", "role": "Software Developer", "skills": [{ "id": 0, "name": "C#" }, { "id": 0, "name": "MVC" }, { "id": 0, "name": "Azure" }, { "id": 0, "name": "AngularJS" }], "Additionalroles": [], "Gender": 0 }, { "id": 0, "firstName": "Michael Riedel", "lastName": null, "displayName": "Michael Riedel ", "profileImageUrl": null, "role": "PM", "skills": [], "Additionalroles": [], "Gender": 0 }, { "id": 0, "firstName": "Marc Rathai", "lastName": null, "displayName": "Marc Rathai ", "profileImageUrl": null, "role": "PM", "skills": [], "Additionalroles": [], "Gender": 0 }];
}
